easybook:
    parameters:
        parser.options:
            code_block_type: fenced
book:
    title: 'Vero aut doloremque dolorum natus.'
    author: 'Author da Silva'
    language: en
    publication_date: null
    generator:
        name: CodePub
        version: 1
    contents:
        -
            element: cover
        -
            element: dedication
            content: dedication.md
        -
            element: toc
        -
            element: chapter
            number: 1
            content: 1.md
        -
            element: chapter
            number: 2
            content: 2.md
    editions:
        kindle:
            extends: ebook
            format: mobi
        ebook:
            format: epub
            include_styles: true
            highlight_cache: true
            highlight_code: false
            labels: [chapter, figure]
            theme: clean
            toc: { deep: 1, elements: [chapter] }
        print:
            format: pdf
            highlight_cache: true
            highlight_code: true
            isbn: null
            include_styles: true
            labels: [chapter, figure]
            margin: { top: 25mm, bottom: 25mm, inner: 30mm, outer: 20mm }
            page_size: A4
            theme: clean
            toc: { deep: 2, elements: [chapter] }
            two_sided: true
        web:
            format: html
            include_styles: true
            highlight_cache: true
            highlight_code: true
            labels: [chapter, figure]
            theme: clean
            toc: { deep: 2, elements: [chapter] }
        website:
            extends: web
            format: html_chunked
            chunk_level: 1
            images_base_dir: /img/doc-en/
        easybook-project.org:
            format: html_chunked
            chunk_level: 2
            images_base_dir: /images/doc-en/
            include_styles: false
            highlight_cache: false
            highlight_code: true
            labels: [chapter, figure]
            theme: clean
            toc: { deep: 2, elements: [chapter] }
